"""Create table todolists and insert the first record there with id=1 and name 'Uncategorized'. Set it as a default value that is being referenced by the foreign key 'todolists_ref' specified on 'todos' table in column 'list_id'.

Revision ID: 0064c993e402
Revises: b4e12d5a63fc
Create Date: 2020-05-12 14:30:32.670739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0064c993e402'
down_revision = 'b4e12d5a63fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO todolists (id, name) VALUES (1, 'Uncategorized')")
    op.add_column('todos', sa.Column('list_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key('todolists_ref', 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todolists_ref', 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
